[package]
name = "tunguska"
version = "0.1.0"
edition = "2021"
authors = ["Jack Willis <jack@attac.us>"]
description = "tuning and temperaments"
license = "MIT"

[dependencies]
num-rational = "0.4"
num-traits = "0.2"

[dev-dependencies]
rusty-hook = "^0.11.2"
